version: '4'

services:
  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - webserver
    volumes:
        - www-html:/var/www/html
        - etc-letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email almas.zhumakhanov.2002a@gmail.com --agree-tos --no-eff-email -d platinum-autorent.com
volumes:
  www-html:
  etc-letsencrypt: