version: '4'

services:
  webserver:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
      - ./certbot/www:/var/www/certbot/:ro